"""empty message

Revision ID: 2c46a22c773e
Revises: a2de18822cd9
Create Date: 2024-02-22 07:08:00.662400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c46a22c773e'
down_revision = 'a2de18822cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spent_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('postal_code', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('aboutme', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('_password_hash')
        batch_op.drop_column('aboutme')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('spent_amount')

    # ### end Alembic commands ###
