"""empty message

Revision ID: 54d891be339e
Revises: 2c46a22c773e
Create Date: 2024-02-22 07:29:31.318110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d891be339e'
down_revision = '2c46a22c773e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('spent_amount')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('password')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spent_amount', sa.NUMERIC(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###
